language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_script:
    - if [ $(phpenv version-name) = "7.0" ]; then phpenv config-rm xdebug.ini; fi
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update --no-interaction

script:
    - vendor/bin/atoum -c .atoum.php.dist

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover